# Generated by Django 2.2.4 on 2020-02-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='책명')),
                ('author', models.CharField(max_length=64, verbose_name='저자')),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('imageurl', models.URLField(verbose_name='이미지  주소')),
                ('link', models.URLField(verbose_name='링크')),
                ('desc', models.TextField(verbose_name='요약')),
            ],
        ),
    ]
